apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: seal-automate
  labels:
    app: seal-automate
webhooks:
- name: seal-automate.default.svc
  admissionReviewVersions:
  - v1
  - v1beta1
  sideEffects: None
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - secrets
  clientConfig:
    service:
      name: seal-automate
      namespace: default
      path: /mutate
  failurePolicy: Fail
  # namespaceSelector를 비우면 모든 네임스페이스에 적용됩니다
  # 특정 네임스페이스에만 적용하려면 아래 주석을 해제하세요
  # namespaceSelector:
  #   matchLabels:
  #     sapcy-sealed-secret: "enabled"

