apiVersion: v1
kind: Service
metadata:
  name: seal-automate
  namespace: default
  labels:
    app: seal-automate
spec:
  ports:
  - port: 443
    targetPort: 8443
    protocol: TCP
    name: webhook
  selector:
    app: seal-automate

